# Generated by Django 2.2 on 2020-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ytdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ytdl_url', models.URLField()),
                ('l_ytdl_title', models.CharField(max_length=200, verbose_name='Title')),
                ('l_pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.SlugField(default=None, unique=True)),
            ],
            options={
                'ordering': ['l_ytdl_title'],
            },
        ),
    ]
