# Generated by Django 2.2 on 2020-11-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytdl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytdl',
            name='l_pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
