# Generated by Django 2.2 on 2020-11-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytdl', '0002_auto_20201114_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytdl',
            name='l_pub_date',
        ),
    ]
