# Generated by Django 2.2 on 2020-11-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytdl', '0003_remove_ytdl_l_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytdl',
            name='l_ytdl_url',
            field=models.URLField(verbose_name='Video URL'),
        ),
    ]
