# Generated by Django 2.2 on 2020-11-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytdl', '0006_userdownloadhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userDownloadHistory',
        ),
    ]
