# Generated by Django 2.2 on 2020-11-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytdl', '0008_userdownloadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytdl',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
